package uk.co.alexks.jeff2.test;

import uk.co.alexks.jeff2.FullSession;
import uk.co.alexks.jeff2.TelemetryListener;

import java.io.File;

public class TestTelemetry {
    //Save telemtery to a file
    //Use this file instead of the UDP socket
    //Compare it to the file generated by the python library (assuming that works)

    public void saveTelemetryToFile(File f){
        FullSession fs = new FullSession();
        TelemetryListener tl = new TelemetryListener(fs, f);
        Thread tlThread = new Thread(tl);
        tlThread.start();
    }
}
